services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend:/app
      - php-app-frontend-node-modules:/app/node_modules
    networks:
      - php-app-frontend-network
    ports:
      - "${EXPOSE_APP_PORT}:3000"

networks:
  php-app-frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.45.1.0/24

volumes:
  php-app-frontend-node-modules:
