import type { Metadata } from 'next'
import React from 'react'
import { Geist, Geist_Mono } from 'next/font/google'
import { AuthProvider } from '@/app/contexts/AuthContext'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "PHP App Frontend",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  )
}
